### ISSUE TITLE
Error importing extension onto Qlik Sense Server 2.1.1

### ISSUE THREAD

**Issue by haty1** [NOD507/SenseDateRangePicker#1]
I receive an error when importing this extension onto our Qlik Sense Server v2.1.1.

**Comment by NOD507** [comment]
Hi thanks to Alex Karlsson for the heads up "There is a bug in 2.1 related to the acceptable file-extensions (or mime types more specifically) that can be imported into QRS. You can either run this https://github.com/stefanwalther/qrs-mime or remove any files which are not .html/.css/.js or images from the extension."



Delete the readme.md and the fonts folder if you dont follow the link to add the mime types to your senseserver.


Also if you download the zip file here everything is in a subfolder you have to zip it without the folder.
