### ISSUE TITLE
Out of screen presentation

### ISSUE THREAD

**Issue by veglar** [NOD507/SenseDateRangePicker#2]
![image](https://cloud.githubusercontent.com/assets/8819782/13629549/1f32d8e2-e5da-11e5-9b29-fd690ce4ecef.png)

The extension object will in sometimes render outside of the Qlik sense application window. If you look at my attached picture you'll see that the predefined periods continues below my application window. In this case it would be better to render it horizontally.

**Comment by NOD507** [comment]
fixed on 1.1.4
