### ISSUE TITLE
Selecting date does not work with Qlik Sense 3.0

### ISSUE THREAD

**Issue by rstepeck** [NOD507/SenseDateRangePicker#4]

**Comment by Kielland** [comment]
Yep! Same problem here! Not functioning in Qlik Sense 3.0! (And since this is one of the most important extensions out there, we're probably quite a few people with this issue!.)

Thx
Tor

**Comment by Kielland** [comment]
I wonder if this is related to a new issue that I have in Qlik Sense 3.0..

I get this message in the console: **Language 'nb' not supported, falling back to 'en-US'**

![bilde2](https://cloud.githubusercontent.com/assets/15069116/16519573/5fd4e6ba-3f8a-11e6-8173-b1f152e4a9a7.png)

**Comment by Kielland** [comment]
Solved the problem by using the date function: =Date([DateField]).

**Comment by NOD507** [comment]
Hi guys i have been very busy this week, tried the extension today on desktop 3.0 and its working fine for me. Maybe rstepeck  have the same issue with the date format? if you can send me the qvf to look at it

**Comment by Kielland** [comment]
Hi! No stress, thanks for checking in even when busy. Now that I found a workaround, it's no big problem anymore! I've posted it on branch. If Qlik resolves (or tells me how to resolve) the 'language not supported issue', i'll post back here to tell whether this was the problem.

Thx
Tor
