### ISSUE TITLE
End Date selection always 1 day off

### ISSUE THREAD

**Issue by bhill2625** [NOD507/SenseDateRangePicker#5]
I am having some issues with this extension that seem to be calendar related or maybe timezone.  When choosing a single date, nothing is actually ever filtered in the application.  When choosing a range of dates, the end date selection is always 1 day short of the actual selection.  Example; I select a date range of 1/1/16 thru 1/5/16 in the UI.  The data filtered is actually 1/1/16 thru 1/4/16.

Qlik Sense Server 3.0

Any ideas?

**Comment by NOD507** [comment]
please send me the qvf just with the date field to check it out

**Comment by NOD507** [comment]
no answer on this one, could not replicate. closing.
